"""Generate embedded demo assets for the device app so on-device recognition is
meaningful (real pet photos, not synthetic gradients).

Picks N pets from data/train, K images each, resizes to 96x96 RGB, and writes
a C array into app/velapaw/assets/velapaw_assets.{c,h}. The device camera HAL
serves these frames; the TFLM backend runs the real model on them.

    python gen_device_assets.py --pets abyssinian beagle --per-pet 5
"""

import argparse
import glob
import os
import numpy as np
import tensorflow as tf

APP_ASSETS = "../app/velapaw/assets"
SIZE = 96   # overridden by --size in main()


def load_rgb(path):
    img = tf.keras.utils.load_img(path, color_mode="rgb", target_size=(SIZE, SIZE))
    return np.asarray(img, np.uint8)  # HWC RGB uint8


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="data/train")
    ap.add_argument("--pets", nargs="+", default=["abyssinian", "beagle"])
    ap.add_argument("--per-pet", type=int, default=5)
    ap.add_argument("--size", type=int, default=96)
    args = ap.parse_args()

    global SIZE
    SIZE = args.size

    os.makedirs(APP_ASSETS, exist_ok=True)
    imgs, pet_of, names = [], [], []
    for pi, pet in enumerate(args.pets):
        files = sorted(glob.glob(os.path.join(args.data, pet, "*")))[:args.per_pet]
        if not files:
            raise SystemExit(f"no images for pet '{pet}' in {args.data}")
        names.append(pet)
        for f in files:
            try:
                imgs.append(load_rgb(f)); pet_of.append(pi)
            except Exception:
                continue
    n = len(imgs)
    print(f"[assets] {len(names)} pets, {n} images @ {SIZE}x{SIZE}x3")

    h = os.path.join(APP_ASSETS, "velapaw_assets.h")
    c = os.path.join(APP_ASSETS, "velapaw_assets.c")
    with open(h, "w") as f:
        f.write("/* Generated by host/gen_device_assets.py - real pet frames for the\n"
                " * emulator demo (96x96x3 RGB uint8, HWC). Do not edit by hand. */\n")
        f.write("#ifndef VELAPAW_ASSETS_H\n#define VELAPAW_ASSETS_H\n#include <stdint.h>\n\n")
        f.write(f"#define VELAPAW_ASSET_W {SIZE}\n#define VELAPAW_ASSET_H {SIZE}\n")
        f.write("#define VELAPAW_ASSET_C 3\n")
        f.write(f"#define VELAPAW_NUM_PETS {len(names)}\n")
        f.write(f"#define VELAPAW_NUM_IMAGES {n}\n\n")
        f.write(f"extern const uint8_t g_velapaw_images[{n}][{SIZE*SIZE*3}];\n")
        f.write(f"extern const int g_velapaw_image_pet[{n}];\n")
        f.write(f"extern const char *const g_velapaw_pet_names[{len(names)}];\n\n")
        f.write("#endif\n")

    with open(c, "w") as f:
        f.write('#include "velapaw_assets.h"\n\n')
        f.write(f"const char *const g_velapaw_pet_names[{len(names)}] = {{")
        f.write(", ".join(f'"{nm}"' for nm in names))
        f.write("};\n\n")
        f.write(f"const int g_velapaw_image_pet[{n}] = {{")
        f.write(", ".join(str(p) for p in pet_of))
        f.write("};\n\n")
        f.write(f"const uint8_t g_velapaw_images[{n}][{SIZE*SIZE*3}] = {{\n")
        for im in imgs:
            flat = im.reshape(-1)
            f.write("  {" + ",".join(str(int(v)) for v in flat) + "},\n")
        f.write("};\n")

    sz = os.path.getsize(c) / 1e6
    print(f"[assets] wrote {c} ({sz:.1f} MB) and {h}")


if __name__ == "__main__":
    main()
