/* Generated by host/gen_device_assets.py - real pet frames for the
 * emulator demo (96x96x3 RGB uint8, HWC). Do not edit by hand. */
#ifndef VELAPAW_ASSETS_H
#define VELAPAW_ASSETS_H
#include <stdint.h>

#define VELAPAW_ASSET_W 128
#define VELAPAW_ASSET_H 128
#define VELAPAW_ASSET_C 3
#define VELAPAW_NUM_PETS 2
#define VELAPAW_NUM_IMAGES 10

extern const uint8_t g_velapaw_images[10][49152];
extern const int g_velapaw_image_pet[10];
extern const char *const g_velapaw_pet_names[2];

#endif
